export const FINANCIAL_MODULE = 'FINANCIAL MODULE';
export const CHECKLIST_MODULE = 'CHECKLIST MODULE';
export const ITINERARY_MODULE = 'ITINERARY MODULE';

export enum ModuleType {
  FINANCIALS_INDIVIDUAL_BALANCES,
  FINANCIALS_GROUP_PAYMENTS,
  FINANCIALS_GROUP_SETTLEMENTS,
  CHECKLIST_MODULE,
  ITINERARY_MODULE,
}
