export const FINANCIAL_MODULE = 'FINANCIAL MODULE';
export const CHECKLIST_MODULE = 'CHECKLIST MODULE';
export const ITINERARY_MODULE = 'ITINERARY MODULE';

export enum GroupFinancialsTab {
  FINANCIALS_GROUP_PAYMENTS_TAB,
  FINANCIALS_GROUP_LENDING_TAB,
}
