"""empty message

Revision ID: 14b78cd8c498
Revises: 7d7e59dd79db
Create Date: 2024-03-05 01:10:09.999059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b78cd8c498'
down_revision = '7d7e59dd79db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('trips')
    with op.batch_alter_table('TripUsers', schema=None) as batch_op:
        batch_op.drop_constraint('TripUsers_trip_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Trips', ['trip_id'], ['id'])

    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('group_payments', schema=None) as batch_op:
        batch_op.drop_constraint('group_payments_trip_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_payments_trip_id_fkey', 'trips', ['trip_id'], ['id'])

    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('TripUsers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('TripUsers_trip_id_fkey', 'trips', ['trip_id'], ['id'])

    op.create_table('trips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trips_pkey'),
    sa.UniqueConstraint('uuid', name='trips_uuid_key')
    )
    op.drop_table('Trips')
    # ### end Alembic commands ###
