"""empty message

Revision ID: 2ec75e3ba82e
Revises: 37c6312123ba
Create Date: 2024-03-04 23:42:26.268421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec75e3ba82e'
down_revision = '37c6312123ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('lendee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.alter_column('lendee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
