"""empty message

Revision ID: af1620bf8576
Revises: b813703cc2d0
Create Date: 2024-03-06 04:21:56.785284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1620bf8576'
down_revision = 'b813703cc2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outstanding_payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'outstanding_payments', ['outstanding_payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('outstanding_payment_id')

    # ### end Alembic commands ###
