"""empty message

Revision ID: b3a03ab9accf
Revises: 81329e8ef099
Create Date: 2024-03-01 01:54:04.499968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3a03ab9accf'
down_revision = '81329e8ef099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_payments')
    op.drop_table('group_payment_lendees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_payment_lendees',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('lendee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_returned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lendee_id'], ['users.id'], name='group_payment_lendees_lendee_id_fkey'),
    sa.ForeignKeyConstraint(['payment_id'], ['group_payments.payment_id'], name='group_payment_lendees_payment_id_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='group_payment_lendees_pkey')
    )
    op.create_table('group_payments',
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_returned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('lender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], name='group_payments_lender_id_fkey'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], name='group_payments_trip_id_fkey'),
    sa.PrimaryKeyConstraint('payment_id', name='group_payments_pkey'),
    sa.UniqueConstraint('uuid', name='group_payments_uuid_key')
    )
    # ### end Alembic commands ###
