"""empty message

Revision ID: e8d73cf3a973
Revises: 488a002ac4a4
Create Date: 2024-03-05 01:17:20.445665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8d73cf3a973'
down_revision = '488a002ac4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('Users')
    op.drop_table('Trips')
    with op.batch_alter_table('TripUsers', schema=None) as batch_op:
        batch_op.drop_constraint('TripUsers_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('TripUsers_trip_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip', ['trip_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])
        batch_op.drop_constraint('group_payment_lendees_lendee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['lendee_id'], ['id'])

    with op.batch_alter_table('group_payments', schema=None) as batch_op:
        batch_op.drop_constraint('group_payments_trip_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('group_payments_lender_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip', ['trip_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['lender_id'], ['id'])

    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.drop_constraint('user_auth_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_auth_user_id_fkey', 'Users', ['user_id'], ['id'])

    with op.batch_alter_table('group_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_payments_lender_id_fkey', 'Users', ['lender_id'], ['id'])
        batch_op.create_foreign_key('group_payments_trip_id_fkey', 'Trips', ['trip_id'], ['id'])

    with op.batch_alter_table('group_payment_lendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_payment_lendees_lendee_id_fkey', 'Users', ['lendee_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('TripUsers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('TripUsers_trip_id_fkey', 'Trips', ['trip_id'], ['id'])
        batch_op.create_foreign_key('TripUsers_user_id_fkey', 'Users', ['user_id'], ['id'])

    op.create_table('Trips',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Trips_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Trips_pkey'),
    sa.UniqueConstraint('uuid', name='Trips_uuid_key')
    )
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Users_pkey'),
    sa.UniqueConstraint('email', name='Users_email_key'),
    sa.UniqueConstraint('uuid', name='Users_uuid_key')
    )
    op.drop_table('user')
    op.drop_table('trip')
    # ### end Alembic commands ###
